### PR TITLE
Add some reserved kws

### PR DESCRIPTION
**Pull request by jazi007**
Adding some keyword reserved by rust

and may be a question why using `typename_` and not `r#typename` ?

### CODE REVIEW

**Comment by ytakano** [comment]
Thank you for your contribution!

> and may be a question why using typename_ and not r#typename ?

It makes sense.
Can you fix and send PR to use r#typename?

**Comment by jazi007** [comment]
> 

Hello @ytakano,

working on it, ping you once done, please do not merge this yet

**Comment by jazi007** [comment]
@ytakano 

Done, please review it carefully :-)
I tested the changes with: [msgtest](https://github.com/tier4/safe_drive_tutorial/tree/main/msgtest)
I also removed the pub from typedef to avoid ambiguous glob reexports warnings

`mangle` divided into 2 functions one for types and the other for files and modules

let me know if anything is wrong or that needs enhancments

**Comment by ytakano** [comment]
@jazi007 

Thank you very much!
I tested and it worked well.

I have published the newest version to [crates.io](https://crates.io/crates/safe_drive_msg), and you can use this by updating [cargo-ament-build](https://github.com/tier4/cargo-ament-build) for safe_drive.

```
$ cd cargo-ament-build
$ cargo update
$ cargo install --path .
```

**Pull request merged**
